export const generators = {
  80000: {
    value: "0",
    vendor: "Khronos",
    comment: "Reserved by Khronos",
  },
  80001: { value: "1", vendor: "LunarG", comment: "Contact TBD" },
  80002: { value: "2", vendor: "Valve", comment: "Contact TBD" },
  80003: {
    value: "3",
    vendor: "Codeplay",
    comment: "Contact Victor Lomuller, victor@codeplay.com",
  },
  80004: {
    value: "4",
    vendor: "NVIDIA",
    comment: "Contact Kerch Holt, kholt@nvidia.com",
  },
  80005: {
    value: "5",
    vendor: "ARM",
    comment: "Contact Alexander Galazin, alexander.galazin@arm.com",
  },
  80006: {
    value: "6",
    vendor: "Khronos",
    tool: "LLVM/SPIR-V Translator",
    comment: "Contact Yaxun (Sam) Liu, yaxun.liu@amd.com",
  },
  80007: {
    value: "7",
    vendor: "Khronos",
    tool: "SPIR-V Tools Assembler",
    comment: "Contact David Neto, dneto@google.com",
  },
  80008: {
    value: "8",
    vendor: "Khronos",
    tool: "Glslang Reference Front End",
    comment: "Contact John Kessenich, johnkessenich@google.com",
  },
  80009: {
    value: "9",
    vendor: "Qualcomm",
    comment: "Contact weifengz@qti.qualcomm.com",
  },
  80010: {
    value: "10",
    vendor: "AMD",
    comment: "Contact Daniel Rakos, daniel.rakos@amd.com",
  },
  80011: {
    value: "11",
    vendor: "Intel",
    comment: "Contact Alexey, alexey.bader@intel.com",
  },
  80012: {
    value: "12",
    vendor: "Imagination",
    comment: "Contact James Jones",
  },
  80013: {
    value: "13",
    vendor: "Google",
    tool: "Shaderc over Glslang",
    comment: "Contact David Neto, dneto@google.com",
  },
  80014: {
    value: "14",
    vendor: "Google",
    tool: "spiregg",
    comment: "Contact Lei Zhang, antiagainst@google.com",
  },
  80015: {
    value: "15",
    vendor: "Google",
    tool: "rspirv",
    comment: "Contact Lei Zhang, antiagainst@gmail.com",
  },
  80016: {
    value: "16",
    vendor: "X-LEGEND",
    tool: "Mesa-IR/SPIR-V Translator",
    comment: "Contact Metora Wang, github:metora/MesaGLSLCompiler",
  },
  80017: {
    value: "17",
    vendor: "Khronos",
    tool: "SPIR-V Tools Linker",
    comment: "Contact David Neto, dneto@google.com",
  },
  80018: {
    value: "18",
    vendor: "Wine",
    tool: "VKD3D Shader Compiler",
    comment: "Contact wine-devel@winehq.org",
  },
  80019: {
    value: "19",
    vendor: "Clay",
    tool: "Clay Shader Compiler",
    comment: "Contact info@clayengine.com",
  },
  80020: {
    value: "20",
    vendor: "W3C WebGPU Group",
    tool: "WHLSL Shader Translator",
    comment: "https://github.com/gpuweb/WHLSL",
  },
  80021: {
    value: "21",
    vendor: "Google",
    tool: "Clspv",
    comment: "Contact David Neto, dneto@google.com",
  },
  80022: {
    value: "22",
    vendor: "Google",
    tool: "MLIR SPIR-V Serializer",
    comment: "Contact Lei Zhang, antiagainst@google.com",
  },
  80023: {
    value: "23",
    vendor: "Google",
    tool: "Tint Compiler",
    comment: "Contact David Neto, dneto@google.com",
  },
};
